# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14OBdcri3pLuF3D751R1PtQuM9L2E-wM_
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

print("Training data shape:", x_train.shape)
print("Test data shape:", x_test.shape)

# Normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# Reshape → (samples, height, width, channels)
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# Display a few images from the dataset
plt.figure(figsize=(10, 10))
for i in range(25):
    plt.subplot(5, 5, i + 1)
    plt.imshow(x_train[i], cmap='gray')
    plt.title(f"Label: {y_train[i]}")
    plt.axis('off')
plt.show()

model = models.Sequential([

    # -------- Convolution Layer 1 --------
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),

    # -------- Pooling Layer 1 --------
    layers.MaxPooling2D(pool_size=(2, 2)),

    # -------- Convolution Layer 2 --------
    layers.Conv2D(64, (3, 3), activation='relu'),

    # -------- Pooling Layer 2 --------
    layers.MaxPooling2D(pool_size=(2, 2)),

    # -------- Flatten --------
    layers.Flatten(),

    # -------- Fully Connected Layer --------
    layers.Dense(128, activation='relu'),

    # -------- Output Layer --------
    layers.Dense(10, activation='softmax')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    x_train,
    y_train,
    epochs=5,
    validation_data=(x_test, y_test)
)

test_loss, test_accuracy = model.evaluate(x_test, y_test)
print("Test Accuracy:", test_accuracy)

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title("Accuracy")

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title("Loss")

plt.show()

import pickle
with open("training_history.pkl", "wb") as f:
    pickle.dump(history.history, f)

print("Training history saved using pickle.")
model.save("mnist_cnn_model.keras")
print("Model saved successfully.")
with open("training_history.pkl", "rb") as f:
    loaded_history = pickle.load(f)

print(loaded_history.keys())



